apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-service
    component: service
    version: "1.0"
spec:
  ports:
  - name: http
    port: 3051
  selector:
    app: db-service
    component: service
    version: "1.0"